# Generated by Django 4.2.1 on 2023-10-04 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Image', models.ImageField(null=True, upload_to='Catagory_Image/%d%m%Y')),
                ('Description', models.CharField(default=' ', max_length=200)),
                ('Status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('Created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=' ', max_length=30)),
                ('Seller', models.CharField(default=' ', max_length=30)),
                ('Product_Image', models.ImageField(null=True, upload_to='Product_Image/%d%m%Y')),
                ('Quantity', models.IntegerField(default=' ')),
                ('Original_price', models.FloatField(default=' ')),
                ('Selling_price', models.FloatField(default=' ')),
                ('Description', models.CharField(default=' ', max_length=200)),
                ('Status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('Trending', models.BooleanField(default=False, help_text='0-default,1-Trending')),
                ('created_at', models.DateField(auto_now=True)),
                ('Catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Source.catagory')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_qty', models.IntegerField()),
                ('created_at', models.DateField(auto_now=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Source.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
