# Generated by Django 4.2.1 on 2023-06-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Source', '0002_alter_catagory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='Status',
            field=models.BooleanField(default=False, help_text='0-show,1-Hidden'),
        ),
    ]
